# Generated by cpp11: do not edit by hand

dust_sirs_alloc <- function(r_pars, pars_multi, step, r_n_particles, n_threads, r_seed, deterministic, device_config) {
  .Call(`_gasworks_dust_sirs_alloc`, r_pars, pars_multi, step, r_n_particles, n_threads, r_seed, deterministic, device_config)
}

dust_sirs_run <- function(ptr, step_end, device) {
  .Call(`_gasworks_dust_sirs_run`, ptr, step_end, device)
}

dust_sirs_simulate <- function(ptr, step_end, device) {
  .Call(`_gasworks_dust_sirs_simulate`, ptr, step_end, device)
}

dust_sirs_set_index <- function(ptr, r_index) {
  .Call(`_gasworks_dust_sirs_set_index`, ptr, r_index)
}

dust_sirs_update_state <- function(ptr, r_pars, r_state, r_step, r_set_initial_state) {
  .Call(`_gasworks_dust_sirs_update_state`, ptr, r_pars, r_state, r_step, r_set_initial_state)
}

dust_sirs_state <- function(ptr, r_index) {
  .Call(`_gasworks_dust_sirs_state`, ptr, r_index)
}

dust_sirs_step <- function(ptr) {
  .Call(`_gasworks_dust_sirs_step`, ptr)
}

dust_sirs_reorder <- function(ptr, r_index) {
  invisible(.Call(`_gasworks_dust_sirs_reorder`, ptr, r_index))
}

dust_sirs_resample <- function(ptr, r_weights) {
  .Call(`_gasworks_dust_sirs_resample`, ptr, r_weights)
}

dust_sirs_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_gasworks_dust_sirs_rng_state`, ptr, first_only, last_only)
}

dust_sirs_set_rng_state <- function(ptr, rng_state) {
  .Call(`_gasworks_dust_sirs_set_rng_state`, ptr, rng_state)
}

dust_sirs_set_data <- function(ptr, data) {
  .Call(`_gasworks_dust_sirs_set_data`, ptr, data)
}

dust_sirs_compare_data <- function(ptr, device) {
  .Call(`_gasworks_dust_sirs_compare_data`, ptr, device)
}

dust_sirs_filter <- function(ptr, save_trajectories, step_snapshot, device) {
  .Call(`_gasworks_dust_sirs_filter`, ptr, save_trajectories, step_snapshot, device)
}

dust_sirs_capabilities <- function() {
  .Call(`_gasworks_dust_sirs_capabilities`)
}

dust_sirs_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_gasworks_dust_sirs_set_n_threads`, ptr, n_threads))
}

dust_sirs_n_state <- function(ptr) {
  .Call(`_gasworks_dust_sirs_n_state`, ptr)
}

dust_sirs_device_info <- function() {
  .Call(`_gasworks_dust_sirs_device_info`)
}
