# Generated by cpp11: do not edit by hand

dust_model_capabilities <- function() {
  .Call(`_gasworks_dust_model_capabilities`)
}

dust_model_gpu_info <- function() {
  .Call(`_gasworks_dust_model_gpu_info`)
}

dust_cpu_model_alloc <- function(r_pars, pars_multi, step, r_n_particles, n_threads, r_seed, deterministic, gpu_config) {
  .Call(`_gasworks_dust_cpu_model_alloc`, r_pars, pars_multi, step, r_n_particles, n_threads, r_seed, deterministic, gpu_config)
}

dust_cpu_model_run <- function(ptr, step_end) {
  .Call(`_gasworks_dust_cpu_model_run`, ptr, step_end)
}

dust_cpu_model_simulate <- function(ptr, step_end) {
  .Call(`_gasworks_dust_cpu_model_simulate`, ptr, step_end)
}

dust_cpu_model_set_index <- function(ptr, r_index) {
  .Call(`_gasworks_dust_cpu_model_set_index`, ptr, r_index)
}

dust_cpu_model_update_state <- function(ptr, r_pars, r_state, r_step, r_set_initial_state) {
  .Call(`_gasworks_dust_cpu_model_update_state`, ptr, r_pars, r_state, r_step, r_set_initial_state)
}

dust_cpu_model_state <- function(ptr, r_index) {
  .Call(`_gasworks_dust_cpu_model_state`, ptr, r_index)
}

dust_cpu_model_step <- function(ptr) {
  .Call(`_gasworks_dust_cpu_model_step`, ptr)
}

dust_cpu_model_reorder <- function(ptr, r_index) {
  invisible(.Call(`_gasworks_dust_cpu_model_reorder`, ptr, r_index))
}

dust_cpu_model_resample <- function(ptr, r_weights) {
  .Call(`_gasworks_dust_cpu_model_resample`, ptr, r_weights)
}

dust_cpu_model_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_gasworks_dust_cpu_model_rng_state`, ptr, first_only, last_only)
}

dust_cpu_model_set_rng_state <- function(ptr, rng_state) {
  .Call(`_gasworks_dust_cpu_model_set_rng_state`, ptr, rng_state)
}

dust_cpu_model_set_data <- function(ptr, data) {
  .Call(`_gasworks_dust_cpu_model_set_data`, ptr, data)
}

dust_cpu_model_compare_data <- function(ptr) {
  .Call(`_gasworks_dust_cpu_model_compare_data`, ptr)
}

dust_cpu_model_filter <- function(ptr, step_end, save_trajectories, step_snapshot, min_log_likelihood) {
  .Call(`_gasworks_dust_cpu_model_filter`, ptr, step_end, save_trajectories, step_snapshot, min_log_likelihood)
}

dust_cpu_model_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_gasworks_dust_cpu_model_set_n_threads`, ptr, n_threads))
}

dust_cpu_model_n_state <- function(ptr) {
  .Call(`_gasworks_dust_cpu_model_n_state`, ptr)
}
